### ISSUE TITLE
[Clion] exe can't find sfml dlls

### ISSUE THREAD

**Issue by johnny12150** [CaffeinatedTech/nibbles#1]
I am using the cmakelists in [nibbles01](https://github.com/CaffeinatedTech/nibbles/blob/main/nibbles-01/CMakeLists.txt).

And I can't even run the demo program from SFML.

![image](https://user-images.githubusercontent.com/22369387/141609209-797e97cf-bd4a-42fe-8dfa-4b72ba6da9ce.png)

**Comment by johnny12150** [comment]
My entire cmake file looks like this.
![image](https://user-images.githubusercontent.com/22369387/141609230-283e68c6-d7f6-47a5-818d-cb861e3f4d47.png)

**Comment by CaffeinatedTech** [comment]
Try adding the `include` directory.

`include_directories(headers /usr/include c:/SFML/include)`

**Comment by johnny12150** [comment]
> Try adding the `include` directory.
> 
> `include_directories(headers /usr/include c:/SFML/include)`

Thanks for the quick reply!
I noticed that my Mingw wasn't exactly the same as you mentioned in the youtube video.
I downgrade it and now everything works fine.
